spring:
  datasource:
    url: jdbc:h2:mem:noteapp
    driver-class-name: org.h2.Driver
    username: debarshee
    password: debarshee
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE