spring:
  datasource:
    url: jdbc:h2:mem:notesapp
    driver-class-name: org.h2.Driver
    username: debarshee
    password: debarshee
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: debarshee
      password: debarshee
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  show-actuator: false